language: java
jdk:
  - oraclejdk8
addons:
  sonarqube: true
env:
  global:
    - secure: ********* 
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=$SONAR_TOKEN
