package br.com.qualityfactory.el.elmd.service.codest;

import java.util.Collection;

import br.com.qualityfactory.el.elmd.domain.Codest;
import br.com.qualityfactory.el.elmd.domain.Model;
import br.com.qualityfactory.el.elmd.exception.ArchitectureProcessELException;
import br.com.qualityfactory.el.elmd.exception.DataBaseELException;

public interface CodestService {

	/**
	 * Recovery all codest
	 * @return return all codest found
	 */
	public Collection<Model> listAll();
	
	/**
	 * Recovery the model with the name of table 
	 * @param tableName name of table
	 * @return Return the model found
	 * @throws ArchitectureProcessELException Exception of process in the execute of reflection for get data
	 * @throws DataBaseELException Exception of database generated by JPA
	 */
	public Model findWithArguments(Codest codest) throws DataBaseELException, ArchitectureProcessELException;
}
